### ISSUE TITLE
How to find edits direction?

### ISSUE THREAD

**Issue by andorxornot** [adobe-research/sam_inversion#5]
Thanks for the article!

For example, how can I manipulate only the pose of a car?

**Comment by anandbhattad** [comment]
Hi! 

Are edits you provide specific to your method (layerwise edits based on segmentation that you get) or can they be applied directly to pretrained stylegan2 w+ space?  For instance, when directly applying those edits to w+ only does not seem to produce realistic results.

![image](https://user-images.githubusercontent.com/16907734/193940503-87af5591-0f1d-407f-9baf-88ec2b5218ee.png)

Thanks,
Anand
