### ISSUE TITLE
Reproduce PSNR score

### ISSUE THREAD

**Issue by Luvata** [adobe-research/sam_inversion#7]
Can you please provide the script to reproduce your PSNR score and run time on 1000 car images (and also on other datasets such as Faces, Cats, Horses) that you mentioned in your paper? I guess it could be highly sensitive to the threshold (and different thresholds between datasets), so I really want to have this evaluation script and config to better measure the performance of your method.
Once again, thank you so much for publishing your code base! Have a nice week!

**Comment by Luvata** [comment]
cc @GaParmar 🥰

**Comment by GaParmar** [comment]
Hi, 

You are indeed correct! The reconstructions PSNR scores would be sensitive to the threshold used. 
For the results reported in our paper, we use a threshold of 0.225. 

Regards,
Gaurav

**Comment by Luvata** [comment]
Thank you for your support!
